/*
NOTE! This code is autogenerated.
Don't manually change this code.
Version [a99d59e2d5e382ce0eb26ea26d3143fdcb9360153b4c254c411fd768b78e9c4c]
*/
package dal

import (
    "context"
    "encoding/gob"
    "database/sql"
    _ "embed"
    "errors"
    "strings"

    "fmt"
    "time"
    

    log "github.com/sirupsen/logrus"
    "github.com/patrickmn/go-cache"
    "github.com/sony/gobreaker"
)

func init() {
	gob.Register(Post{})
}

// Struct representing Post. Do not use these structs directly across services as this struct carries db specific information.
// recommendation: create higher level service layer structs that might look same or very similar instead.
type Post struct {
    ID        int64 `json:"id"` // Auto-incremented number
    Version   int32 `json:"version"` // Only change this value directly in very specific cases.  
    
    Deleted bool `json:"deleted"`
    ExpiresAt time.Time `json:"expires_at"`
    Post string `json:"post"`
    Revoked bool `json:"revoked"`
    TargetAge int8 `json:"target_age"`

    Created   time.Time `json:"created"`
    Updated   time.Time `json:"updated"`

}

// PostRepository defines the interface for the Post.
// Use this interface in your services to easily mock the database.
type PostRepository interface {
    CreateTable(ctx context.Context) error
    GetByID(ctx context.Context, id int64) (*Post, error)

    InvalidateCache(entity *Post)
    FlushListCache()
    FlushAllCache()
    Create(ctx context.Context, entity *Post) (*Post, error)
    CreateBulk(ctx context.Context, entities []*Post) ([]*Post, error)
    Update(ctx context.Context, entity *Post) error
    Delete(ctx context.Context, entity *Post) error
    ListById(ctx context.Context, startID int64, pageSize int) ([]*Post, error)
    CountListById(ctx context.Context, ) (int64, error)
    RecentPosts(ctx context.Context, targetAge int8, startID int64, pageSize int) ([]*Post, error)
    CountRecentPosts(ctx context.Context, targetAge int8) (int64, error)
    DeleteExpired(ctx context.Context, cutoff time.Time, limit int) (int64, error)

}

type postRepository struct {
    dbProvider          DBProvider
    cache               *cache.Cache  // Simple TTL cache for single items, for inmemory cache management
  	listCache           *cache.Cache // Cache for lists. Simple TTL cache, for inmemory cache management
    countCache          *cache.Cache // Cache for counts. Simple TTL cache, for inmemory cache management
    cacheProvider       CacheProvider
    configProvider      ConfigProvider
	dbBreaker           *gobreaker.CircuitBreaker
    telemetryProvider TelemetryProvider
}

// NewPostRepository now returns the PostRepository interface.
func NewPostRepository(
    provider DBProvider, 
    cacheProvider CacheProvider,
    configProvider ConfigProvider, 
    dbSettings gobreaker.Settings, 
    telemetry TelemetryProvider) PostRepository {

    if configProvider == nil {
        configProvider = DefaultConfigProvider{}
    }

    if cacheProvider == nil {
        cacheProvider = NoopCacheProvider{}
    }

    if telemetry == nil {
		telemetry = NoopTelemetryProvider{}
	}

    if dbSettings.Name == "" {
        dbSettings.Name = "post_dal"
    }
    if dbSettings.ReadyToTrip == nil {
        dbSettings.ReadyToTrip = func(counts gobreaker.Counts) bool {
            return counts.ConsecutiveFailures > 5
        }
    }
    if dbSettings.OnStateChange == nil {
		dbSettings.OnStateChange = OnCircuitBreakerStateChange
	}

    dbSettings.IsSuccessful = func(err error) bool {
		if err == nil {
			return true
		}
		// If the record just doesn't exist, the database is perfectly healthy
		if errors.Is(err, ErrNotFound) {
			return true
		}
		return false
	}


    if dbSettings.Timeout == 0 {
        dbSettings.Timeout = time.Second * 30
    }

    // Default expiration is 5 minutes and cleanup of 10 minutes
   	singleCache := cache.New(5*time.Minute, 10*time.Minute)
	listCache := cache.New(5*time.Minute, 10*time.Minute)
    countCache := cache.New(5*time.Minute, 10*time.Minute)

    newDAL := &postRepository{
        dbProvider:     provider,
        cache:          singleCache,
        listCache:      listCache,
        countCache:     countCache,
        cacheProvider:  cacheProvider,
        configProvider: configProvider,
		dbBreaker:      gobreaker.NewCircuitBreaker(dbSettings),
        telemetryProvider: telemetry,
    }

    // initialize cache invalidation handler
    cacheProvider.OnCacheInvalidated("post", newDAL.onCacheInvalidated)
    cacheProvider.OnCacheFlushList("post", newDAL.onCacheFlushList)
    cacheProvider.OnCacheFlushItem("post", newDAL.onCacheFlushItem)

    return newDAL
}

func (d *postRepository) getCacheKey(id int64) string {
    return fmt.Sprintf("post_id:%d", id)
}



func (d *postRepository) InvalidateCache(entity *Post) {
    cacheKey := d.getCacheKey(entity.ID)
	d.cache.Delete(cacheKey)

	// Invalidate cache entry across instances
	d.cacheProvider.InvalidateCache("post", cacheKey)
}

func (d *postRepository) FlushListCache() {
    d.listCache.Flush()
    d.countCache.Flush()

    // Invalidate cache entry across instances
    d.cacheProvider.FlushListCache("post")
}

// FlushAllCache clears both list/count caches AND single-item caches locally, 
// and broadcasts the flush to other instances.
func (d *postRepository) FlushAllCache() {
	d.cache.Flush()
	d.listCache.Flush()
	d.countCache.Flush()

	// Invalidate cache entries across instances
	d.cacheProvider.FlushListCache("post")
	d.cacheProvider.FlushItemCache("post")
}

// Handles cache_flush_item. Just clears the single items cache locally.
func (d *postRepository) onCacheFlushItem() {
	d.cache.Flush()
}

// Handles cache invalidations. Just remove cached entry by key
func (d *postRepository) onCacheInvalidated(key string) {
    d.cache.Delete(key)
}

// Handles cache_flush_list. Just clears all lists cache.
func (d *postRepository) onCacheFlushList() {
    d.listCache.Flush()
    d.countCache.Flush()
}




//go:embed post.sql
var schemaPost string

func (d *postRepository) CreateTable(ctx context.Context) error {
	// Get write database connection
	dbs := d.dbProvider.AllDatabases("post", "write")

	for _, db := range dbs {
		// First check if table exists
		exists, err := d.tableExists(ctx, db)
		if err != nil {
			return fmt.Errorf("failed to check table existence: %w", err)
		}
		if exists {
		    log.Infof("CreateTable: table [%s] already exist", "post")
			return nil
		}

		// 1. Strip out comment lines completely BEFORE splitting by semicolons
		var cleanLines []string
		for _, line := range strings.Split(schemaPost, "\n") {
			trimmedLine := strings.TrimSpace(line)
			// Skip empty lines and lines that start with a comment hash
			if trimmedLine == "" || strings.HasPrefix(trimmedLine, "#") {
				continue
			}
			cleanLines = append(cleanLines, line)
		}
		
		// 2. Re-join the clean lines, then split by semicolon
		cleanSchema := strings.Join(cleanLines, "\n")
		statements := strings.Split(cleanSchema, ";")

		// 3. Execute the actual statements
		for _, stmt := range statements {
			stmt = strings.TrimSpace(stmt)
			if stmt == "" {
				continue
			}

			_, err = db.ExecContext(ctx, stmt)
			if err != nil {
				return fmt.Errorf("failed to execute SQL statement %q: %w", stmt, err)
			}
		}
	}
	log.Infof("CreateTable: table [%s] created", "post")

	return nil
}

func (d *postRepository) tableExists(ctx context.Context, db *sql.DB) (bool, error) {
	query := `
		SELECT 1
		FROM information_schema.tables 
		WHERE table_schema = DATABASE() 
		AND table_name = 'posts'
	`

	var exists bool
	err := db.QueryRowContext(ctx, query).Scan(&exists)
	if errors.Is(err, sql.ErrNoRows) {
		return false, nil
	}
	if err != nil {
		return false, fmt.Errorf("failed to query table existence: %w", err)
	}

	return exists, nil
}




func (d *postRepository) Create(ctx context.Context, entity *Post) (*Post, error) {
    if d.configProvider.BlockedWrites("post") {
        return nil, ErrOperationBlocked
    }

	if entity.ID > 0 {
		return nil, fmt.Errorf("postRepository.Create failed as ID > 0")
	}

	d.telemetryProvider.IncDALOperation("post", "create")

	_, err := d.dbBreaker.Execute(func() (interface{}, error) {
		return d.create(ctx, entity)
	})

	if err != nil {
		return nil, err
	}

	d.setCached(entity)

	// All lists cache should be flushed.
	d.FlushListCache()

	return entity, err
}

func (d *postRepository) create(ctx context.Context, entity *Post) (*Post, error) {
	const operation = "create"
	start := time.Now()

	now := time.Now().Truncate(time.Second)
	entity.Created = now
	entity.Updated = now
	
	// Auto-generate UID fields if they are not provided

	query := `
		INSERT INTO posts (deleted,expires_at,post,revoked,target_age,
created,updated)
		VALUES (?,?,?,?,?,?,?)
	`

    db, dbErr := d.dbProvider.GetDatabase("post", true);
    if dbErr != nil {
		d.telemetryProvider.IncDBError("post", operation)		
        return nil, dbErr
    }

	result, err := db.ExecContext(ctx, query,entity.Deleted, entity.ExpiresAt, entity.Post, entity.Revoked, entity.TargetAge,
		entity.Created, entity.Updated)

	if err != nil {
		d.telemetryProvider.IncDBError("post", operation)
		return nil, fmt.Errorf("failed to insert Post: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		d.telemetryProvider.IncDBError("post", operation)
		return nil, fmt.Errorf("failed to get last insert ID: %w", err)
	}

	entity.ID = id	
	d.telemetryProvider.IncDBRequest("post", operation)	
	d.telemetryProvider.ObserveDBLatency("post", operation, time.Since(start).Seconds())	
	return entity, nil
}



func (d *postRepository) CreateBulk(ctx context.Context, entities []*Post) ([]*Post, error) {
	if d.configProvider.BlockedWrites("post") {
		return nil, ErrOperationBlocked
	}

	const operation = "create_bulk"
	d.telemetryProvider.IncDALOperation("post", operation)

	result, err := d.dbBreaker.Execute(func() (interface{}, error) {
		return d.createBulk(ctx, entities)
	})

	if err != nil {
		return nil, err
	}

	// All lists cache should be flushed.
	d.FlushListCache()

	return result.([]*Post), err
}

func (d *postRepository) createBulk(ctx context.Context, entities []*Post) ([]*Post, error) {
    const operation = "create_bulk"
    start := time.Now()

    if len(entities) == 0 {
        return nil, fmt.Errorf("empty entities list")
    }

    // Get the database connection once, outside the loop
    db, dbErr := d.dbProvider.GetDatabase("post", true)
    if dbErr != nil {
        d.telemetryProvider.IncDBError("post", operation)
        return nil, dbErr
    }

    now := time.Now().Truncate(time.Second)
    batchSize := 500 // Safe limit to prevent exceeding MySQL's max placeholders

    // Process entities in chunks
    for i := 0; i < len(entities); i += batchSize {
        end := i + batchSize
        if end > len(entities) {
            end = len(entities)
        }
        
        chunk := entities[i:end]

        // Prepare data and parameters scoped ONLY to this chunk
        valuePlaceholders := make([]string, 0, len(chunk))
        // Dynamically calculate fields per entity: custom columns + 2 (created, updated)
        params := make([]interface{}, 0, len(chunk)*(5 + 2)) 

        for _, entity := range chunk {
            if entity.ID > 0 {
                return nil, fmt.Errorf("entity with existing ID in bulk create")
            }

            entity.Created = now
            entity.Updated = now

			// Auto-generate UID fields if they are not provided

            valuePlaceholders = append(valuePlaceholders, "(?,?,?,?,?,?,?)")
            params = append(params,
                entity.Deleted,
                entity.ExpiresAt,
                entity.Post,
                entity.Revoked,
                entity.TargetAge,
                entity.Created,
                entity.Updated,
            )
        }

        query := fmt.Sprintf(`
            INSERT INTO posts
            (deleted,expires_at,post,revoked,target_age,
created,updated)
            VALUES %s
        `, strings.Join(valuePlaceholders, ","))

        result, err := db.ExecContext(ctx, query, params...)
        if err != nil {
            d.telemetryProvider.IncDBError("post", operation)
            return nil, fmt.Errorf("failed to bulk insert posts chunk: %w", err)
        }

        // Get generated IDs (works for MySQL/SQLite)
        lastID, err := result.LastInsertId()
        if err != nil {
            return nil, fmt.Errorf("failed to get last insert ID for chunk: %w", err)
        }

        rowsAffected, err := result.RowsAffected()
        if err != nil {
            return nil, fmt.Errorf("failed to get rows affected for chunk: %w", err)
        }

        if rowsAffected != int64(len(chunk)) {
            return nil, fmt.Errorf("mismatch between inserted rows and entity count in chunk")
        }

        // Assign generated IDs sequentially to the current chunk
        for j := range chunk {
            chunk[j].ID = lastID + int64(j)
			d.setCached(chunk[j])
        }
    }

    d.telemetryProvider.IncDBRequest("post", operation) 
    d.telemetryProvider.ObserveDBLatency("post", operation, time.Since(start).Seconds())    
    return entities, nil
}



// ErrNotFound is returned in case there was nothing to update; either missing id or newer version of entity is already stored.
func (d *postRepository) Update(ctx context.Context, entity *Post) error {
    if d.configProvider.BlockedWrites("post") {
        return ErrOperationBlocked
    }

	const operation = "update"
	d.telemetryProvider.IncDALOperation("post", operation)

	

	// Perform the update in DB.
	_, err2 := d.dbBreaker.Execute(func() (interface{}, error) {
		return nil, d.update(ctx, entity)
	})

	if err2 != nil {
		return err2
	}

	

	// Lets clear item from cache on other instances and here
	d.InvalidateCache(entity)
	d.FlushListCache()

	entity.Version++
	// our entity can become part of local cache
	d.setCached(entity)

	return nil
}

func (d *postRepository) update(ctx context.Context, entity *Post) error {
	const operation = "update"
	start := time.Now()

	entity.Updated = time.Now()

	query := `
		UPDATE posts
		SET deleted = ?,expires_at = ?,post = ?,revoked = ?,target_age = ?, updated=?, version = version + 1
		WHERE id = ? AND version = ? 
	`

    db, dbErr := d.dbProvider.GetDatabase("post", true);
    if dbErr != nil {
		d.telemetryProvider.IncDBError("post", operation)
        return dbErr
    }

	res, err := db.ExecContext(ctx, query,entity.Deleted, entity.ExpiresAt, entity.Post, entity.Revoked, entity.TargetAge,
	entity.Updated, entity.ID, entity.Version)

	if err != nil {
		d.telemetryProvider.IncDBError("post", operation)
		return fmt.Errorf("failed to update Post: %w", err)
	}

	rowsAffected, err := res.RowsAffected()
	if err != nil {
		d.telemetryProvider.IncDBError("post", operation)
		return fmt.Errorf("failed to get rows affected: %w", err)
	}

	if rowsAffected == 0 {
		// clean out cache for specific ID to limit stale cache entries
		d.InvalidateCache(entity)
		return ErrNotFound
	}

	d.telemetryProvider.ObserveDBLatency("post", operation, time.Since(start).Seconds())	

	return nil
}



// Deletes entity by id,
// returns ErrNotFound in case nothing is deleted.
func (d *postRepository) Delete(ctx context.Context, entity *Post) error {
    if d.configProvider.BlockedWrites("post") {
        return ErrOperationBlocked
    }

	if entity.ID == 0 {
		// nothing can be deleted as entity is not created.
		return ErrNotFound
	}

	const operation = "delete"
	d.telemetryProvider.IncDALOperation("post", operation)

	_, err := d.dbBreaker.Execute(func() (interface{}, error) {
		return nil, d.delete(ctx, entity.ID)
	})

	if err != nil {
		return err
	}

	// Lets clear item from cache and on next use use DB as source of truth
	d.InvalidateCache(entity)
	d.FlushListCache()

	return err
}

func (d *postRepository) delete(ctx context.Context, id int64) error {
	start := time.Now()
	const operation = "delete"

	
	query := `
		DELETE FROM posts
		WHERE id = ?
	`
	

    db, dbErr := d.dbProvider.GetDatabase("post", true);
    if dbErr != nil {
		d.telemetryProvider.IncDBError("post", operation)
        return dbErr
    }

	res, err := db.ExecContext(ctx, query, id)
	if err != nil {
		d.telemetryProvider.IncDBError("post", operation)
		return fmt.Errorf("failed to delete post: %w", err)
	}

	rowsAffected, err := res.RowsAffected()
	if err != nil {
		d.telemetryProvider.IncDBError("post", operation)
		return fmt.Errorf("failed to get rows affected: %w", err)
	}

	if rowsAffected == 0 {
		return ErrNotFound
	}

	d.telemetryProvider.IncDBRequest("post", operation)	
	d.telemetryProvider.ObserveDBLatency("post", operation, time.Since(start).Seconds())	
	return nil
}






func (d *postRepository) GetByID(ctx context.Context, id int64) (*Post, error) {
    if d.configProvider.BlockedReads("post") {
        return nil, ErrOperationBlocked
    }

    const operation = "get_by_id"
    d.telemetryProvider.IncDALOperation("post", operation)

	// Load from cache
    cachedEntity, _ := d.getByIDCached(id)
    if cachedEntity != nil {
        return cachedEntity, nil
    }

	// Fallback to database if cache miss or decoding fails
	result, err := d.dbBreaker.Execute(func() (interface{}, error) {
		return d.getByID(ctx, id)
	})

	if err != nil {
		return nil, err
	}

	entity, ok := result.(*Post)
    if !ok {
        return nil, fmt.Errorf("invalid type")
    }

    _ = d.setCached(entity)

    return entity, err
}

func (d *postRepository) setCached(entity *Post) error {
    // if we have not reached the maximum number of items set the cache. otherwise expirations will
	// handle this
    itemCount := d.cache.ItemCount()
    if itemCount < 1000000 {
        cacheKey := d.getCacheKey(entity.ID)

        // Store in cache with new format        
        d.telemetryProvider.IncCacheWrite("post")
        d.telemetryProvider.SetCacheSize("post", float64(itemCount+1))        

        copy := *entity
		d.cache.Set(cacheKey, &copy, time.Second*300)
    }

    return nil
}

// Gets entity from cache only or return nil
func (d *postRepository) getByIDCached(id int64) (*Post, error) {
    const operation = "get_by_id"
    cacheKey := d.getCacheKey(id)
    val, found := d.cache.Get(cacheKey)
    if found {
        entity, ok := val.(*Post)
        if !ok {
            return nil, fmt.Errorf("postRepository.GetById: Cache returned wrong type")
        }

        d.telemetryProvider.IncCacheHit("post", operation)        
        copy := *entity
        return &copy, nil
    }

    // Cache missed or error during fetching cached data
    d.telemetryProvider.IncCacheMiss("post", operation)        	

    return nil, nil
}

func (d *postRepository) getByID(ctx context.Context, id int64) (*Post, error) {
    const operation = "get_by_id"
    dbStart := time.Now();

    query := `
        SELECT id, version, deleted, expires_at, post, revoked, target_age, created, updated
        FROM posts
        WHERE id = ? 
    `

    db, dbErr := d.dbProvider.GetDatabase("post", false);
    if dbErr != nil {
        d.telemetryProvider.IncDBError("post", operation)
        return nil, dbErr
    }

    row := db.QueryRowContext(ctx, query, id)
    var entity Post
    err := row.Scan(
        &entity.ID,
        &entity.Version,&entity.Deleted,&entity.ExpiresAt,&entity.Post,&entity.Revoked,&entity.TargetAge,
        &entity.Created,
        &entity.Updated,
        
    )
    if err != nil {
        if errors.Is(err, sql.ErrNoRows) {
            return nil, ErrNotFound
        }
        d.telemetryProvider.IncDBError("post", operation)
        return nil, fmt.Errorf("failed to get Post by ID: %w", err)
    }

    d.telemetryProvider.IncDBRequest("post", operation)	
    d.telemetryProvider.ObserveDBLatency("post", operation, time.Since(dbStart).Seconds())	
    return &entity, nil
}




func (d *postRepository) ListById(ctx context.Context, startID int64, pageSize int) ([]*Post, error) {
    if d.configProvider.BlockedReads("post") {
        return nil, ErrOperationBlocked
    }

	const operation = "list_by_id"
	d.telemetryProvider.IncDALOperation("post", operation)

    cacheKey := fmt.Sprintf("post_list_by_id:%d:%d", startID, pageSize)
    val, found := d.listCache.Get(cacheKey)
    if found {
        entityIDs, ok := val.([]int64)
        if !ok {
            return nil, fmt.Errorf("postRepository.ListById: Cache returned wrong type; expected array ID type")
        }

        var entities []*Post
        missingEntries := false
        for _, id := range entityIDs {
            entity, err := d.getByIDCached(id)
            if err != nil {
                // failed using cache
                return nil, err
            }

            if entity == nil {
                // we have one or more missing entity in cache somehow. reload the whole list.
                missingEntries = true
                break
            }

            entities = append(entities, entity)
        }

        if !missingEntries {
            d.telemetryProvider.IncCacheHit("post", operation)        
            return entities, nil
        }
    }

    // Otherwise, it's a cache miss or decode error
     d.telemetryProvider.IncCacheMiss("post", operation)       

    // 2) Fallback to DB
    result, err := d.dbBreaker.Execute(func() (interface{}, error) {
        return d.listById(ctx, startID, pageSize)
    })

    if err != nil {
        // DB also failed
        return nil, err
    }

    entities := result.([]*Post)
    // Store Cache. cacheKey = user_list_by_id:startID:pageSize.
	// Stored is array of entity IDs.
	var entityIDs []int64
	for _, entity := range entities {
		entityIDs = append(entityIDs, entity.ID)
        // cache each entity individualy
        d.setCached(entity)
	}
	d.listCache.Set(cacheKey, entityIDs, time.Second*60)

    return entities, nil
}

func (d *postRepository) listById(ctx context.Context, startID int64, pageSize int) ([]*Post, error) {
    const operation = "list_by_id"
	dbStart := time.Now()

    var query string

    // if startID is zero then query is different for pagination
    if startID == 0 {
        query = `SELECT id, version, deleted, expires_at, post, revoked, target_age, created, updated FROM posts ORDER BY id LIMIT ?`
    } else {
        query = `SELECT id, version, deleted, expires_at, post, revoked, target_age, created, updated FROM posts WHERE id > ? ORDER BY id LIMIT ?`
    }

    db, dbErr := d.dbProvider.GetDatabase("post", false);
    if dbErr != nil {
        d.telemetryProvider.IncDBError("post", operation)
        return nil, dbErr
    }

    var rows *sql.Rows
    var err error

    if startID == 0 {
	    rows, err = db.QueryContext(ctx, query, pageSize)
    } else {
        rows, err = db.QueryContext(ctx, query, startID, pageSize)
    }

	if err != nil {
        d.telemetryProvider.IncDBError("post", operation)
		return nil, fmt.Errorf("failed to query posts: %w", err)
	}
	defer rows.Close()

	var entities []*Post
	for rows.Next() {
		var entity Post
		err := rows.Scan(
			&entity.ID,
            &entity.Version,
            &entity.Deleted,
            &entity.ExpiresAt,
            &entity.Post,
            &entity.Revoked,
            &entity.TargetAge,
            &entity.Created,
            &entity.Updated,
            
		)
		if err != nil {
            d.telemetryProvider.IncDBError("post", operation)
			return nil, fmt.Errorf("failed to scan Post: %w", err)
		}
		entities = append(entities, &entity)
	}

	if err = rows.Err(); err != nil {
        d.telemetryProvider.IncDBError("post", operation)
		return nil, fmt.Errorf("rows error: %w", err)
	}

    d.telemetryProvider.IncDBRequest("post", operation)	
    d.telemetryProvider.ObserveDBLatency("post", operation, time.Since(dbStart).Seconds())	
	return entities, nil
}



func (d *postRepository) RecentPosts(ctx context.Context, targetAge int8, startID int64, pageSize int) ([]*Post, error) {
    if d.configProvider.BlockedReads("post") {
        return nil, ErrOperationBlocked
    }

	const operation = "recent_posts"
	d.telemetryProvider.IncDALOperation("post", operation)

    cacheKey := fmt.Sprintf("post_recent_posts:%v:%d:%d", targetAge, startID, pageSize)
    val, found := d.listCache.Get(cacheKey)
    if found {
        entityIDs, ok := val.([]int64)
        if !ok {
            return nil, fmt.Errorf("postRepository.RecentPosts: Cache returned wrong type; expected array ID type")
        }

        var entities []*Post
        missingEntries := false
        for _, id := range entityIDs {
            entity, err := d.getByIDCached(id)
            if err != nil {
                // failed using cache
                return nil, err
            }

            if entity == nil {
                // we have one or more missing entity in cache somehow. reload the whole list.
                missingEntries = true
                break
            }

            entities = append(entities, entity)
        }

        if !missingEntries {
            d.telemetryProvider.IncCacheHit("post", operation)        
            return entities, nil
        }
    }

    // Otherwise, it's a cache miss or decode error
     d.telemetryProvider.IncCacheMiss("post", operation)       

    // 2) Fallback to DB
    result, err := d.dbBreaker.Execute(func() (interface{}, error) {
        return d.recentPosts(ctx, targetAge, startID, pageSize)
    })

    if err != nil {
        // DB also failed
        return nil, err
    }

    entities := result.([]*Post)
    // Store Cache. cacheKey = user_list_by_id:startID:pageSize.
	// Stored is array of entity IDs.
	var entityIDs []int64
	for _, entity := range entities {
		entityIDs = append(entityIDs, entity.ID)
        // cache each entity individualy
        d.setCached(entity)
	}
	d.listCache.Set(cacheKey, entityIDs, time.Second*60)

    return entities, nil
}

func (d *postRepository) recentPosts(ctx context.Context, targetAge int8, startID int64, pageSize int) ([]*Post, error) {
    const operation = "recent_posts"
	dbStart := time.Now()

    var query string

    // if startID is zero then query is different for pagination
    if startID == 0 {
        query = `SELECT id, version, deleted, expires_at, post, revoked, target_age, created, updated FROM posts WHERE (deleted = 0 and target_age = ?) ORDER BY created, id LIMIT ?`
    } else {
        query = `SELECT id, version, deleted, expires_at, post, revoked, target_age, created, updated FROM posts WHERE (deleted = 0 and target_age = ?) AND id > ? ORDER BY created, id LIMIT ?`
    }

    db, dbErr := d.dbProvider.GetDatabase("post", false);
    if dbErr != nil {
        d.telemetryProvider.IncDBError("post", operation)
        return nil, dbErr
    }

    var rows *sql.Rows
    var err error

    if startID == 0 {
	    rows, err = db.QueryContext(ctx, query, targetAge, pageSize)
    } else {
        rows, err = db.QueryContext(ctx, query, targetAge, startID, pageSize)
    }

	if err != nil {
        d.telemetryProvider.IncDBError("post", operation)
		return nil, fmt.Errorf("failed to query posts: %w", err)
	}
	defer rows.Close()

	var entities []*Post
	for rows.Next() {
		var entity Post
		err := rows.Scan(
			&entity.ID,
            &entity.Version,
            &entity.Deleted,
            &entity.ExpiresAt,
            &entity.Post,
            &entity.Revoked,
            &entity.TargetAge,
            &entity.Created,
            &entity.Updated,
            
		)
		if err != nil {
            d.telemetryProvider.IncDBError("post", operation)
			return nil, fmt.Errorf("failed to scan Post: %w", err)
		}
		entities = append(entities, &entity)
	}

	if err = rows.Err(); err != nil {
        d.telemetryProvider.IncDBError("post", operation)
		return nil, fmt.Errorf("rows error: %w", err)
	}

    d.telemetryProvider.IncDBRequest("post", operation)	
    d.telemetryProvider.ObserveDBLatency("post", operation, time.Since(dbStart).Seconds())	
	return entities, nil
}



// Count function for the specific list
func (d *postRepository) CountListById(ctx context.Context, ) (int64, error) {
	if d.configProvider.BlockedReads("post") {
		return 0, ErrOperationBlocked
	}

	const operation = "count_list_by_id"
	d.telemetryProvider.IncDALOperation("post", operation)
	
	cacheKey := fmt.Sprintf("post_count_list_by_id")
	val, found := d.countCache.Get(cacheKey)
	if found {
		count, ok := val.(int64)
		if !ok {
			return 0, fmt.Errorf("postRepository.CountListById: Cache returned wrong type; expected int64")
		}

		d.telemetryProvider.IncCacheHit("post", operation)        
		return count, nil
	}

	// Otherwise, it's a cache miss or decode error
	 d.telemetryProvider.IncCacheMiss("post", operation)       

	// 2) Fallback to DB
	count, err := d.dbBreaker.Execute(func() (interface{}, error) {
		return d.countListById(ctx, )
	})

	if err != nil {
		// DB also failed
		return 0, err
	}

	d.countCache.Set(cacheKey, count, time.Second*60)

	return count.(int64), nil
}

func (d *postRepository) countListById(ctx context.Context, ) (int64, error) {
	const operation = "count_list_by_id"
	dbStart := time.Now()

	// if startID is zero then query is different for pagination
	query := `SELECT count(*) FROM posts`

	db, dbErr := d.dbProvider.GetDatabase("post", false)
	if dbErr != nil {
		d.telemetryProvider.IncDBError("post", operation)
		return 0, dbErr
	}

	var err error
	var count int64

	row := db.QueryRowContext(ctx, query, )

	err = row.Scan(
		&count,
	)

	if err != nil {
		d.telemetryProvider.IncDBError("post", operation)
		return 0, fmt.Errorf("failed to query posts: %w", err)
	}

	d.telemetryProvider.IncDBRequest("post", operation)	
	d.telemetryProvider.ObserveDBLatency("post", operation, time.Since(dbStart).Seconds())	
	return count, nil
}



// Count function for the specific list
func (d *postRepository) CountRecentPosts(ctx context.Context, targetAge int8) (int64, error) {
	if d.configProvider.BlockedReads("post") {
		return 0, ErrOperationBlocked
	}

	const operation = "count_recent_posts"
	d.telemetryProvider.IncDALOperation("post", operation)
	
	cacheKey := fmt.Sprintf("post_count_recent_posts:%v", targetAge)
	val, found := d.countCache.Get(cacheKey)
	if found {
		count, ok := val.(int64)
		if !ok {
			return 0, fmt.Errorf("postRepository.CountRecentPosts: Cache returned wrong type; expected int64")
		}

		d.telemetryProvider.IncCacheHit("post", operation)        
		return count, nil
	}

	// Otherwise, it's a cache miss or decode error
	 d.telemetryProvider.IncCacheMiss("post", operation)       

	// 2) Fallback to DB
	count, err := d.dbBreaker.Execute(func() (interface{}, error) {
		return d.countRecentPosts(ctx, targetAge)
	})

	if err != nil {
		// DB also failed
		return 0, err
	}

	d.countCache.Set(cacheKey, count, time.Second*60)

	return count.(int64), nil
}

func (d *postRepository) countRecentPosts(ctx context.Context, targetAge int8) (int64, error) {
	const operation = "count_recent_posts"
	dbStart := time.Now()

	// if startID is zero then query is different for pagination
	query := `SELECT count(*) FROM posts WHERE (deleted = 0 and target_age = ?)`

	db, dbErr := d.dbProvider.GetDatabase("post", false)
	if dbErr != nil {
		d.telemetryProvider.IncDBError("post", operation)
		return 0, dbErr
	}

	var err error
	var count int64

	row := db.QueryRowContext(ctx, query, targetAge)

	err = row.Scan(
		&count,
	)

	if err != nil {
		d.telemetryProvider.IncDBError("post", operation)
		return 0, fmt.Errorf("failed to query posts: %w", err)
	}

	d.telemetryProvider.IncDBRequest("post", operation)	
	d.telemetryProvider.ObserveDBLatency("post", operation, time.Since(dbStart).Seconds())	
	return count, nil
}
















// DeleteExpired executes a custom bulk delete operation.
// 
// PERFORMANCE NOTE: To prevent database locks, undo-log bloat, and replication lag, 
// this operation requires a limit parameter. If the provided limit is <= 0 or > 5000, 
// it will be automatically clamped to 5000.
// 
// Example usage for bulk deletion:
//
//	batchSize := 5000
//	for {
//		rowsAffected, err := repo.DeleteExpired(ctx, /* args */, batchSize)
//		if err != nil {
//			// handle error appropriately
//			break
//		}
//		if rowsAffected == 0 {
//			break // All matching rows have been processed
//		}
//		time.Sleep(100 * time.Millisecond) // Yield database resources between batches
//	}
func (d *postRepository) DeleteExpired(ctx context.Context, cutoff time.Time, limit int) (int64, error) {
    if d.configProvider.BlockedWrites("post") {
        return 0, ErrOperationBlocked
    }

    // Clamp the limit to a safe range
    if limit <= 0 || limit > 5000 {
        limit = 5000
    }

    const operation = "delete_expired"
    d.telemetryProvider.IncDALOperation("post", operation)

    result, err := d.dbBreaker.Execute(func() (interface{}, error) {
        return d.deleteExpired(ctx, cutoff, limit)
    })

    if err != nil {
        return 0, err
    }

    rowsAffected := result.(int64)
    
    if rowsAffected > 0 {
        d.FlushAllCache() 
    }

    return rowsAffected, nil
}

func (d *postRepository) deleteExpired(ctx context.Context, cutoff time.Time, limit int) (int64, error) {
    const operation = "delete_expired"
    dbStart := time.Now()

    // Inject the sanitized limit directly into the SQL string
    query := `DELETE FROM posts WHERE expires_at < ? OR (revoked = true AND updated < ?)` + fmt.Sprintf(" LIMIT %d", limit)

    db, dbErr := d.dbProvider.GetDatabase("post", true)
    if dbErr != nil {
        d.telemetryProvider.IncDBError("post", operation)
        return 0, dbErr
    }

    
    res, err := db.ExecContext(ctx, query, cutoff, cutoff)
    
    
    if err != nil {
        d.telemetryProvider.IncDBError("post", operation)
        return 0, fmt.Errorf("failed to execute custom delete %s: %w", operation, err)
    }

    rowsAffected, err := res.RowsAffected()
    if err != nil {
        d.telemetryProvider.IncDBError("post", operation)
        return 0, fmt.Errorf("failed to get rows affected: %w", err)
    }

    d.telemetryProvider.IncDBRequest("post", operation)
    d.telemetryProvider.ObserveDBLatency("post", operation, time.Since(dbStart).Seconds())
    
    return rowsAffected, nil
}




